# Configuration for Alacritty, the GPU enhanced terminal emulator.

window:
  padding:
    x: 16
    y: 16

font:
  normal:
    family: GNU Unifont

  bold:
    style: Regular

  size: 11.0

colors:
  primary:
    background: '0xe5e5d3'
    foreground: '0x000000'
  normal:
    black:   '0x073642'
    red:     '0xdc322f'
    green:   '0x208000'
    yellow:  '0x806000'
    blue:    '0x2072ac'
    magenta: '0xd33682'
    cyan:    '0x1f7a72'
    white:   '0xeee8d5'

draw_bold_text_with_bright_colors: false
